//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_bases.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoBasesJAREntities1 : DbContext
    {
        public ProyectoBasesJAREntities1()
            : base("name=ProyectoBasesJAREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alineacion> alineacion { get; set; }
        public virtual DbSet<anotadores> anotadores { get; set; }
        public virtual DbSet<arbitro> arbitro { get; set; }
        public virtual DbSet<arbitrojuego> arbitrojuego { get; set; }
        public virtual DbSet<cambios> cambios { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<club> club { get; set; }
        public virtual DbSet<clubcompeticiontemporada> clubcompeticiontemporada { get; set; }
        public virtual DbSet<competicion> competicion { get; set; }
        public virtual DbSet<competiciontemporada> competiciontemporada { get; set; }
        public virtual DbSet<contrato> contrato { get; set; }
        public virtual DbSet<correo> correo { get; set; }
        public virtual DbSet<direccion> direccion { get; set; }
        public virtual DbSet<entrenador> entrenador { get; set; }
        public virtual DbSet<entrenadortitulo> entrenadortitulo { get; set; }
        public virtual DbSet<especialidad> especialidad { get; set; }
        public virtual DbSet<especialidadjugador> especialidadjugador { get; set; }
        public virtual DbSet<fechacalendario> fechacalendario { get; set; }
        public virtual DbSet<federacion> federacion { get; set; }
        public virtual DbSet<funcclubcomptemporada> funcclubcomptemporada { get; set; }
        public virtual DbSet<funcionariodeportivo> funcionariodeportivo { get; set; }
        public virtual DbSet<histalineacion> histalineacion { get; set; }
        public virtual DbSet<histanotadores> histanotadores { get; set; }
        public virtual DbSet<histarbitrojuego> histarbitrojuego { get; set; }
        public virtual DbSet<histcambios> histcambios { get; set; }
        public virtual DbSet<histclubcompeticiontemporada> histclubcompeticiontemporada { get; set; }
        public virtual DbSet<histcompeticiontemporada> histcompeticiontemporada { get; set; }
        public virtual DbSet<histfechacalendario> histfechacalendario { get; set; }
        public virtual DbSet<histfuncclubcomptemporada> histfuncclubcomptemporada { get; set; }
        public virtual DbSet<histjuego> histjuego { get; set; }
        public virtual DbSet<juego> juego { get; set; }
        public virtual DbSet<jugador> jugador { get; set; }
        public virtual DbSet<oferta> oferta { get; set; }
        public virtual DbSet<sociosclub> sociosclub { get; set; }
        public virtual DbSet<telefono> telefono { get; set; }
        public virtual DbSet<temporada> temporada { get; set; }
        public virtual DbSet<tituloacademico> tituloacademico { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
