
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_bases.Models
{

using System;
    using System.Collections.Generic;
    
public partial class clubcompeticiontemporada
{

    public string idclub { get; set; }

    public int posicion { get; set; }

    public Nullable<int> golesafavor { get; set; }

    public Nullable<int> golesencontra { get; set; }

    public int idtemporada { get; set; }

    public string idcompeticion { get; set; }

    public Nullable<int> puntos { get; set; }

    public string usrcreador { get; set; }

    public System.DateTime fchcreacion { get; set; }

    public string usrmodificador { get; set; }

    public Nullable<System.DateTime> fchmodificacion { get; set; }



    public virtual club club { get; set; }

    public virtual competiciontemporada competiciontemporada { get; set; }

    public virtual usuario usuario { get; set; }

    public virtual usuario usuario1 { get; set; }

}

}
