
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Proyecto_bases.Models
{

using System;
    using System.Collections.Generic;
    
public partial class juego
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public juego()
    {

        this.alineacion = new HashSet<alineacion>();

        this.anotadores = new HashSet<anotadores>();

        this.arbitrojuego = new HashSet<arbitrojuego>();

        this.cambios = new HashSet<cambios>();

    }


    public int idjuego { get; set; }

    public string jugado { get; set; }

    public Nullable<int> golescasa { get; set; }

    public Nullable<int> golesvisita { get; set; }

    public string idclubcasa { get; set; }

    public string idclubvisita { get; set; }

    public int idcalendario { get; set; }

    public string sinopsis { get; set; }

    public string usrcreador { get; set; }

    public Nullable<System.DateTime> fchcreacion { get; set; }

    public string usrmodificador { get; set; }

    public Nullable<System.DateTime> fchmodificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<alineacion> alineacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<anotadores> anotadores { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<arbitrojuego> arbitrojuego { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<cambios> cambios { get; set; }

    public virtual club club { get; set; }

    public virtual club club1 { get; set; }

    public virtual fechacalendario fechacalendario { get; set; }

    public virtual usuario usuario { get; set; }

    public virtual usuario usuario1 { get; set; }

}

}
