//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class histjuego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public histjuego()
        {
            this.histalineacions = new HashSet<histalineacion>();
            this.histanotadores = new HashSet<histanotadore>();
            this.histarbitrojuegoes = new HashSet<histarbitrojuego>();
            this.histcambios = new HashSet<histcambio>();
        }
    
        public decimal idjuego { get; set; }
        public string jugado { get; set; }
        public Nullable<decimal> golescasa { get; set; }
        public Nullable<decimal> golesvisita { get; set; }
        public string idclubcasa { get; set; }
        public string idclubvisita { get; set; }
        public decimal idcalendario { get; set; }
        public string sinopsis { get; set; }
        public string usrcreador { get; set; }
        public System.DateTime fchcreacion { get; set; }
        public string usrmodificador { get; set; }
        public Nullable<System.DateTime> fchmodificacion { get; set; }
    
        public virtual club club { get; set; }
        public virtual club club1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<histalineacion> histalineacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<histanotadore> histanotadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<histarbitrojuego> histarbitrojuegoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<histcambio> histcambios { get; set; }
        public virtual histfechacalendario histfechacalendario { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
