//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBases.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectoBaseEntities : DbContext
    {
        public proyectoBaseEntities()
            : base("name=proyectoBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alineacion> alineacions { get; set; }
        public virtual DbSet<anotadore> anotadores { get; set; }
        public virtual DbSet<arbitro> arbitroes { get; set; }
        public virtual DbSet<arbitrojuego> arbitrojuegoes { get; set; }
        public virtual DbSet<cambio> cambios { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<club> clubs { get; set; }
        public virtual DbSet<clubcompeticiontemporada> clubcompeticiontemporadas { get; set; }
        public virtual DbSet<competicion> competicions { get; set; }
        public virtual DbSet<competiciontemporada> competiciontemporadas { get; set; }
        public virtual DbSet<contrato> contratoes { get; set; }
        public virtual DbSet<correo> correos { get; set; }
        public virtual DbSet<direccion> direccions { get; set; }
        public virtual DbSet<entrenador> entrenadors { get; set; }
        public virtual DbSet<entrenadortitulo> entrenadortituloes { get; set; }
        public virtual DbSet<especialidad> especialidads { get; set; }
        public virtual DbSet<especialidadjugador> especialidadjugadors { get; set; }
        public virtual DbSet<fechacalendario> fechacalendarios { get; set; }
        public virtual DbSet<federacion> federacions { get; set; }
        public virtual DbSet<funcclubcomptemporada> funcclubcomptemporadas { get; set; }
        public virtual DbSet<funcionariodeportivo> funcionariodeportivoes { get; set; }
        public virtual DbSet<histalineacion> histalineacions { get; set; }
        public virtual DbSet<histanotadore> histanotadores { get; set; }
        public virtual DbSet<histarbitrojuego> histarbitrojuegoes { get; set; }
        public virtual DbSet<histcambio> histcambios { get; set; }
        public virtual DbSet<histclubcompeticiontemporada> histclubcompeticiontemporadas { get; set; }
        public virtual DbSet<histcompeticiontemporada> histcompeticiontemporadas { get; set; }
        public virtual DbSet<histfechacalendario> histfechacalendarios { get; set; }
        public virtual DbSet<histfuncclubcomptemporada> histfuncclubcomptemporadas { get; set; }
        public virtual DbSet<histjuego> histjuegoes { get; set; }
        public virtual DbSet<juego> juegoes { get; set; }
        public virtual DbSet<jugador> jugadors { get; set; }
        public virtual DbSet<oferta> ofertas { get; set; }
        public virtual DbSet<sociosclub> sociosclubs { get; set; }
        public virtual DbSet<telefono> telefonoes { get; set; }
        public virtual DbSet<temporada> temporadas { get; set; }
        public virtual DbSet<tituloacademico> tituloacademicoes { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
