//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPaises.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class proyectoBases2Entities5 : DbContext
    {
        public proyectoBases2Entities5()
            : base("name=proyectoBases2Entities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<persona> persona { get; set; }
    
        public virtual ObjectResult<consulta1_Result> consulta1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consulta1_Result>("consulta1");
        }
    
        public virtual ObjectResult<consulta2_Result> consulta2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consulta2_Result>("consulta2");
        }
    
        public virtual int insercionPersonas(Nullable<int> numPais)
        {
            var numPaisParameter = numPais.HasValue ?
                new ObjectParameter("numPais", numPais) :
                new ObjectParameter("numPais", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insercionPersonas", numPaisParameter);
        }
    
        public virtual ObjectResult<paginarPaises_Result> paginarPaises(Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter pageCount)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paginarPaises_Result>("paginarPaises", pageIndexParameter, pageSizeParameter, pageCount);
        }
    
        public virtual ObjectResult<paginarPersonasPorPais_Result> paginarPersonasPorPais(Nullable<decimal> idPais, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter pageCount)
        {
            var idPaisParameter = idPais.HasValue ?
                new ObjectParameter("idPais", idPais) :
                new ObjectParameter("idPais", typeof(decimal));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paginarPersonasPorPais_Result>("paginarPersonasPorPais", idPaisParameter, pageIndexParameter, pageSizeParameter, pageCount);
        }
    }
}
