<?xml version="1.0" encoding="utf-8"?><Database Name="proyectoBase" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sqlmaster\sqlmaster;Initial Catalog=proyectoBase;Persist Security Info=True;User ID=proyectoBases" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="proyectoBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.club" Member="clubs">
    <Type Name="club">
      <Column Name="idclub" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fchfundado" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="idfederacion" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="club_contrato" Member="contratos" ThisKey="idclub" OtherKey="idclub" Type="contrato" />
      <Association Name="club_alineacion" Member="alineacions" ThisKey="idclub" OtherKey="idclub" Type="alineacion" />
      <Association Name="club_anotadore" Member="anotadores" ThisKey="idclub" OtherKey="idclub" Type="anotadore" />
      <Association Name="club_clubcompeticiontemporada" Member="clubcompeticiontemporadas" ThisKey="idclub" OtherKey="idclub" Type="clubcompeticiontemporada" />
      <Association Name="club_contrato1" Member="contrato1s" ThisKey="idclub" OtherKey="idclub" Type="contrato1" />
      <Association Name="club_funcclubcomptemporada" Member="funcclubcomptemporadas" ThisKey="idclub" OtherKey="idclub" Type="funcclubcomptemporada" />
      <Association Name="club_juego" Member="juegos" ThisKey="idclub" OtherKey="idclubcasa" Type="juego" />
      <Association Name="club_juego1" Member="juegos1" ThisKey="idclub" OtherKey="idclubvisita" Type="juego" />
      <Association Name="federacion_club" Member="federacion" ThisKey="idfederacion" OtherKey="idfederacion" Type="federacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.contrato" Member="contratos">
    <Type Name="contrato">
      <Column Name="validez" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="importe" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fchinicio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="fchfinal" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idclub" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idfuncionario" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="club_contrato" Member="club" ThisKey="idclub" OtherKey="idclub" Type="club" IsForeignKey="true" />
      <Association Name="funcionariodeportivo_contrato" Member="funcionariodeportivo" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="funcionariodeportivo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.alineacion" Member="alineacions">
    <Type Name="alineacion">
      <Column Name="idfuncionario" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idjuego" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rendimiento" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="idclub" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="club_alineacion" Member="club" ThisKey="idclub" OtherKey="idclub" Type="club" IsForeignKey="true" />
      <Association Name="juego_alineacion" Member="juego" ThisKey="idjuego" OtherKey="idjuego" Type="juego" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="jugador_alineacion" Member="jugador" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="jugador" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.anotadores" Member="anotadores">
    <Type Name="anotadore">
      <Column Name="idfuncionario" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="idjuego" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="minjuego" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="video" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idclub" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="club_anotadore" Member="club" ThisKey="idclub" OtherKey="idclub" Type="club" IsForeignKey="true" />
      <Association Name="juego_anotadore" Member="juego" ThisKey="idjuego" OtherKey="idjuego" Type="juego" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="jugador_anotadore" Member="jugador" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="jugador" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.arbitro" Member="arbitros">
    <Type Name="arbitro">
      <Column Name="idarbitro" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rendimiento" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idcategoria" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="arbitro_arbitrojuego" Member="arbitrojuegos" ThisKey="idarbitro" OtherKey="idarbitro" Type="arbitrojuego" />
    </Type>
  </Table>
  <Table Name="dbo.arbitrojuego" Member="arbitrojuegos">
    <Type Name="arbitrojuego">
      <Column Name="calificacion" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="idjuego" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idarbitro" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="arbitro_arbitrojuego" Member="arbitro" ThisKey="idarbitro" OtherKey="idarbitro" Type="arbitro" IsForeignKey="true" />
      <Association Name="juego_arbitrojuego" Member="juego" ThisKey="idjuego" OtherKey="idjuego" Type="juego" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.clubcompeticiontemporada" Member="clubcompeticiontemporadas">
    <Type Name="clubcompeticiontemporada">
      <Column Name="idclub" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="posicion" Type="System.Decimal" DbType="Decimal(2,0) NOT NULL" CanBeNull="false" />
      <Column Name="golesafavor" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="golesencontra" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="idtemporada" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idcompeticion" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="puntos" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="club_clubcompeticiontemporada" Member="club" ThisKey="idclub" OtherKey="idclub" Type="club" IsForeignKey="true" />
      <Association Name="competiciontemporada_clubcompeticiontemporada" Member="competiciontemporada" ThisKey="idtemporada,idcompeticion" OtherKey="idtemporada,idcompeticion" Type="competiciontemporada" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.competicion" Member="competicions">
    <Type Name="competicion">
      <Column Name="idcompeticion" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="usrmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="competicion_competiciontemporada" Member="competiciontemporadas" ThisKey="idcompeticion" OtherKey="idcompeticion" Type="competiciontemporada" />
    </Type>
  </Table>
  <Table Name="dbo.competiciontemporada" Member="competiciontemporadas">
    <Type Name="competiciontemporada">
      <Column Name="idcompeticion" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idtemporada" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="competiciontemporada_clubcompeticiontemporada" Member="clubcompeticiontemporadas" ThisKey="idtemporada,idcompeticion" OtherKey="idtemporada,idcompeticion" Type="clubcompeticiontemporada" />
      <Association Name="competiciontemporada_fechacalendario" Member="fechacalendarios" ThisKey="idtemporada,idcompeticion" OtherKey="idtemporada,idcompeticion" Type="fechacalendario" />
      <Association Name="competiciontemporada_funcclubcomptemporada" Member="funcclubcomptemporadas" ThisKey="idtemporada,idcompeticion" OtherKey="idtemporada,idcompeticion" Type="funcclubcomptemporada" />
      <Association Name="competicion_competiciontemporada" Member="competicion" ThisKey="idcompeticion" OtherKey="idcompeticion" Type="competicion" IsForeignKey="true" />
      <Association Name="temporada_competiciontemporada" Member="temporada" ThisKey="idtemporada" OtherKey="idtemporada" Type="temporada" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.contrato" Member="contrato1s">
    <Type Name="contrato1">
      <Column Name="validez" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="importe" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fchinicio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="fchfinal" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idclub" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idfuncionario" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="club_contrato1" Member="club" ThisKey="idclub" OtherKey="idclub" Type="club" IsForeignKey="true" />
      <Association Name="funcionariodeportivo_contrato1" Member="funcionariodeportivo" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="funcionariodeportivo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.fechacalendario" Member="fechacalendarios">
    <Type Name="fechacalendario">
      <Column Name="idcompeticion" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="idcalendario" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idtemporada" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="fechacalendario_juego" Member="juegos" ThisKey="idcalendario" OtherKey="idcalendario" Type="juego" />
      <Association Name="competiciontemporada_fechacalendario" Member="competiciontemporada" ThisKey="idtemporada,idcompeticion" OtherKey="idtemporada,idcompeticion" Type="competiciontemporada" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.entrenador" Member="entrenadors">
    <Type Name="entrenador">
      <Column Name="idfuncionario" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fchiniciocarrera" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="jugadorjuventud" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="funcionariodeportivo_entrenador" Member="funcionariodeportivo" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="funcionariodeportivo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.federacion" Member="federacions">
    <Type Name="federacion">
      <Column Name="idfederacion" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fchfundada" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="federacion_club" Member="clubs" ThisKey="idfederacion" OtherKey="idfederacion" Type="club" />
    </Type>
  </Table>
  <Table Name="dbo.funcclubcomptemporada" Member="funcclubcomptemporadas">
    <Type Name="funcclubcomptemporada">
      <Column Name="idfuncionario" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idclub" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="goles" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="sinopsis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="idtemporada" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idcompeticion" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="competiciontemporada_funcclubcomptemporada" Member="competiciontemporada" ThisKey="idtemporada,idcompeticion" OtherKey="idtemporada,idcompeticion" Type="competiciontemporada" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="club_funcclubcomptemporada" Member="club" ThisKey="idclub" OtherKey="idclub" Type="club" IsForeignKey="true" />
      <Association Name="funcionariodeportivo_funcclubcomptemporada" Member="funcionariodeportivo" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="funcionariodeportivo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.funcionariodeportivo" Member="funcionariodeportivos">
    <Type Name="funcionariodeportivo">
      <Column Name="idfuncionario" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="foto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fchnacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="funcionariodeportivo_contrato" Member="contratos" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="contrato" />
      <Association Name="funcionariodeportivo_contrato1" Member="contrato1s" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="contrato1" />
      <Association Name="funcionariodeportivo_entrenador" Member="entrenador" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="entrenador" Cardinality="One" />
      <Association Name="funcionariodeportivo_funcclubcomptemporada" Member="funcclubcomptemporadas" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="funcclubcomptemporada" />
      <Association Name="funcionariodeportivo_jugador" Member="jugador" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="jugador" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.juego" Member="juegos">
    <Type Name="juego">
      <Column Name="idjuego" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="jugado" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="golescasa" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="golesvisita" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="idclubcasa" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="idclubvisita" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="idcalendario" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="sinopsis" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="juego_alineacion" Member="alineacions" ThisKey="idjuego" OtherKey="idjuego" Type="alineacion" />
      <Association Name="juego_anotadore" Member="anotadores" ThisKey="idjuego" OtherKey="idjuego" Type="anotadore" />
      <Association Name="juego_arbitrojuego" Member="arbitrojuegos" ThisKey="idjuego" OtherKey="idjuego" Type="arbitrojuego" />
      <Association Name="club_juego" Member="club" ThisKey="idclubcasa" OtherKey="idclub" Type="club" IsForeignKey="true" />
      <Association Name="club_juego1" Member="club1" ThisKey="idclubvisita" OtherKey="idclub" Type="club" IsForeignKey="true" />
      <Association Name="fechacalendario_juego" Member="fechacalendario" ThisKey="idcalendario" OtherKey="idcalendario" Type="fechacalendario" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.jugador" Member="jugadors">
    <Type Name="jugador">
      <Column Name="idfuncionario" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rendimiento" Type="System.Decimal" DbType="Decimal(3,0) NOT NULL" CanBeNull="false" />
      <Column Name="peso" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="altura" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="jugador_alineacion" Member="alineacions" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="alineacion" />
      <Association Name="jugador_anotadore" Member="anotadores" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="anotadore" />
      <Association Name="funcionariodeportivo_jugador" Member="funcionariodeportivo" ThisKey="idfuncionario" OtherKey="idfuncionario" Type="funcionariodeportivo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.temporada" Member="temporadas">
    <Type Name="temporada">
      <Column Name="idtemporada" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="usrcreador" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fchcreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="usrmodificador" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fchmodificacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="temporada_competiciontemporada" Member="competiciontemporadas" ThisKey="idtemporada" OtherKey="idtemporada" Type="competiciontemporada" />
    </Type>
  </Table>
</Database>